' Part of "Red Ink for Word"
' Copyright (c) LawDigital Ltd., Switzerland. All rights reserved. For license to use see https://redink.ai.

' =============================================================================
' File: DrawioEditorForm.vb
' Purpose: Hosts the diagrams.net / draw.io editor inside a WinForms window using
'          WebView2. Loads a diagram from an XML string (mxfile) generated by the
'          application and allows the user to edit it. On save, the updated XML
'          can be persisted back to a local .drawio file.
'
' Architecture:
'  - WebView2 Host: Uses Microsoft.Web.WebView2.WinForms.WebView2 as an embedded
'    Chromium-based browser to render the web editor.
'  - Local Host HTML: Uses CoreWebView2.NavigateToString() to load an in-memory
'    HTML “host page” controlled by the add-in.
'  - Embed Communication: The host page embeds draw.io in an <iframe> pointing to
'    https://embed.diagrams.net with embed mode enabled and communicates with it
'    via the official HTML5 postMessage protocol (init/load/save/exit).
'  - Event Bridging: The host page forwards relevant events to .NET via
'    window.chrome.webview.postMessage(JSON.stringify(...)) so the add-in can
'    react (e.g., persist XML to disk).
'
' Dependencies:
'  - Microsoft.Web.WebView2 (Core + WinForms): WebView2 hosting and messaging bridge
'  - Newtonsoft.Json: Safe JSON escaping/serialization for XML and messages
'  - SharedLibrary.SharedLibrary.SharedMethods: Branding constants (AN) and icon/logo helpers
'
' Key Members:
'  - InitializeWebViewAsync(): Initializes WebView2 environment and loads host HTML
'  - BuildHostHtml(): Generates the in-memory host page with iframe + postMessage wiring
'  - OnWebMessageReceived(): Receives forwarded events from the host page (save/exit, diagnostics)
'  - SaveDiagram(): Persists draw.io XML to the target .drawio file path
' =============================================================================

Option Strict On
Option Explicit On

Imports System.Diagnostics
Imports System.Drawing
Imports System.IO
Imports System.IO.Compression
Imports System.Windows.Forms
Imports Microsoft.Web.WebView2.Core
Imports Microsoft.Web.WebView2.WinForms
Imports SharedLibrary.SharedLibrary.SharedMethods

Public Class DrawioEditorForm
    Inherits Form

    Private WithEvents webView As WebView2
    Private ReadOnly _xmlContent As String
    Private ReadOnly _saveFilePath As String
    Private ReadOnly _fileName As String

    Private _loadSent As Boolean = False

    Private Const DRAWIO_EMBED_URL As String =
        "https://embed.diagrams.net/?embed=1&proto=json&spin=1&saveAndExit=1&noSaveBtn=0"

    ''' <summary>
    ''' Creates a new draw.io editor window that loads an existing diagram from XML and can save it back to disk.
    ''' </summary>
    ''' <param name="xmlContent">
    ''' The draw.io diagram XML (typically an <c>mxfile</c> document) to load into the embedded editor.
    ''' If <see langword="Nothing"/> is supplied, an empty string is used.
    ''' </param>
    ''' <param name="saveFilePath">Full path to the <c>.drawio</c> file where the updated diagram XML should be saved.</param>
    Public Sub New(xmlContent As String, saveFilePath As String)
        _xmlContent = If(xmlContent, "")
        _saveFilePath = saveFilePath
        _fileName = IO.Path.GetFileNameWithoutExtension(saveFilePath)

        InitializeComponent()
        InitializeWebViewAsync()
    End Sub

    ''' <summary>
    ''' Initializes the WinForms UI for the editor window and creates the embedded <see cref="WebView2"/> control.
    ''' </summary>
    ''' <remarks>
    ''' This method sets form chrome (title, size, icon) and docks the WebView2 instance to fill the client area.
    ''' </remarks>
    Private Sub InitializeComponent()
        Me.Text = $"{AN} - Draw.io Diagram Editor"
        Me.Width = 1400
        Me.Height = 900
        Me.StartPosition = FormStartPosition.CenterScreen
        Me.FormBorderStyle = FormBorderStyle.Sizable

        Try
            Dim bmp As New Bitmap(GetLogoBitmap(LogoType.Standard))
            Me.Icon = Icon.FromHandle(bmp.GetHicon())
        Catch
        End Try

        webView = New WebView2() With {.Dock = DockStyle.Fill}
        Me.Controls.Add(webView)
    End Sub

    ''' <summary>
    ''' Asynchronously initializes WebView2 (including its user data folder) and navigates to the in-memory host HTML page.
    ''' </summary>
    ''' <remarks>
    ''' The host HTML embeds diagrams.net in an <c>&lt;iframe&gt;</c> and forwards postMessage events to .NET using
    ''' <c>window.chrome.webview.postMessage</c>.
    ''' </remarks>
    Private Async Sub InitializeWebViewAsync()
        Try
            Dim userDataFolder As String = IO.Path.Combine(IO.Path.GetTempPath(), "RedInk_WebView2_Drawio")
            IO.Directory.CreateDirectory(userDataFolder)

            Dim env As CoreWebView2Environment = Await CoreWebView2Environment.CreateAsync(Nothing, userDataFolder)
            Await webView.EnsureCoreWebView2Async(env)

            webView.CoreWebView2.Settings.AreDevToolsEnabled = True
            webView.CoreWebView2.Settings.AreDefaultContextMenusEnabled = True

            ' Receive events forwarded from the host HTML (chrome.webview.postMessage)
            AddHandler webView.CoreWebView2.WebMessageReceived, AddressOf OnWebMessageReceived
            AddHandler webView.CoreWebView2.NavigationCompleted, AddressOf OnNavigationCompleted

            Debug.WriteLine("[DrawioEditorForm] Loading local host HTML...")
            Dim html As String = BuildHostHtml(_xmlContent, _fileName)
            webView.CoreWebView2.NavigateToString(html)

        Catch ex As Exception
            Debug.WriteLine($"[DrawioEditorForm] WebView2 init error: {ex.Message}")
            MessageBox.Show(
                $"Could not initialize the diagram editor: {ex.Message}{vbCrLf}{vbCrLf}" &
                $"Your diagram has been saved to:{vbCrLf}{_saveFilePath}",
                $"{AN} - Error",
                MessageBoxButtons.OK,
                MessageBoxIcon.Error)
            Me.Close()
        End Try
    End Sub

    ''' <summary>
    ''' Builds the in-memory HTML host page that embeds diagrams.net (draw.io) and bridges events back to .NET.
    ''' </summary>
    ''' <param name="xml">The diagram XML to be loaded into the embedded editor.</param>
    ''' <param name="title">The diagram title (typically the file name without extension) shown by the editor.</param>
    ''' <returns>
    ''' A complete HTML document string that can be loaded via <see cref="CoreWebView2.NavigateToString"/>.
    ''' </returns>
    ''' <remarks>
    ''' The HTML uses the official diagrams.net embed protocol over <c>window.postMessage</c>.
    ''' On <c>init</c>, it sends a <c>load</c> action containing the diagram XML.
    ''' Save/exit events are forwarded to .NET via WebView2's message bridge.
    ''' </remarks>
    Private Function BuildHostHtml(xml As String, title As String) As String
        ' We control this page -> we can implement the official embed protocol reliably.
        Dim xmlJs As String = Newtonsoft.Json.JsonConvert.SerializeObject(xml)
        Dim titleJs As String = Newtonsoft.Json.JsonConvert.SerializeObject(title)

        Return $"<!doctype html>
<html>
<head>
  <meta charset=""utf-8"">
  <title>{AN} - draw.io</title>
  <style>
    html, body {{ margin:0; padding:0; height:100%; overflow:hidden; }}
    #frame {{ width:100%; height:100%; border:0; }}
  </style>
</head>
<body>
  <iframe id=""frame"" src=""{DRAWIO_EMBED_URL}"" allow=""clipboard-read; clipboard-write""></iframe>

  <script>
    (function() {{
      const frame = document.getElementById('frame');
      const xml = {xmlJs};
      const title = {titleJs};

      function logToHost(obj) {{
        try {{
          if (window.chrome && window.chrome.webview) {{
            window.chrome.webview.postMessage(JSON.stringify(obj));
          }}
        }} catch (e) {{}}
      }}

      window.addEventListener('message', function(evt) {{
        if (!evt || !evt.data) return;
        if (typeof evt.data !== 'string') return;

        // Forward all draw.io events to .NET for debugging
        logToHost({{ event: 'drawio_msg', data: evt.data.substring(0, 400) }});

        let msg = null;
        try {{ msg = JSON.parse(evt.data); }} catch (e) {{ return; }}

        if (msg.event === 'init') {{
          // Load the diagram
          const loadMsg = {{
            action: 'load',
            xml: xml,
            title: title
          }};
          frame.contentWindow.postMessage(JSON.stringify(loadMsg), '*');
          logToHost({{ event: 'ri_loaded_sent' }});
        }}

        if (msg.event === 'save') {{
          // draw.io usually sends xml on save
          logToHost(msg);
        }}

        if (msg.event === 'exit') {{
          logToHost(msg);
        }}
      }}, false);

      logToHost({{ event: 'ri_host_ready' }});
    }})();
  </script>
</body>
</html>"
    End Function

    ''' <summary>
    ''' Handles WebView2 navigation completion to emit diagnostics when the host page finishes loading.
    ''' </summary>
    ''' <param name="sender">The event source.</param>
    ''' <param name="e">Navigation completion information including success state and error status.</param>
    Private Sub OnNavigationCompleted(sender As Object, e As CoreWebView2NavigationCompletedEventArgs)
        If Not e.IsSuccess Then
            Debug.WriteLine($"[DrawioEditorForm] Navigation failed: {e.WebErrorStatus}")
            Return
        End If
        Debug.WriteLine("[DrawioEditorForm] Navigation completed.")
    End Sub


    ''' <summary>
    ''' Receives messages posted from the host HTML (via <c>window.chrome.webview.postMessage</c>)
    ''' and reacts to draw.io lifecycle events such as init, save, and exit.
    ''' </summary>
    ''' <param name="sender">The event source.</param>
    ''' <param name="e">The message event args containing the posted message payload.</param>
    ''' <remarks>
    ''' Messages are expected to be JSON objects with an <c>event</c> field (e.g., <c>init</c>, <c>save</c>, <c>exit</c>).
    ''' On <c>save</c>, the provided XML is persisted using <see cref="SaveDiagram"/>.
    ''' </remarks>
    Private Sub OnWebMessageReceived(sender As Object, e As CoreWebView2WebMessageReceivedEventArgs)
        Try
            Dim messageString As String = e.TryGetWebMessageAsString()
            If String.IsNullOrEmpty(messageString) Then Return

            Debug.WriteLine($"[DrawioEditorForm] <- {If(messageString.Length > 200, messageString.Substring(0, 200), messageString)}")

            Dim message As Dictionary(Of String, Object) = Nothing
            Try
                message = Newtonsoft.Json.JsonConvert.DeserializeObject(Of Dictionary(Of String, Object))(messageString)
            Catch
                message = Nothing
            End Try
            If message Is Nothing Then Return

            Dim evtName As String = Nothing
            If message.ContainsKey("event") Then evtName = TryCast(message("event"), String)
            If String.IsNullOrEmpty(evtName) Then Return

            Select Case evtName
                Case "ri_bridge_ready"
                    Debug.WriteLine("[DrawioEditorForm] Bridge ready (JS -> .NET works). Waiting for draw.io init...")

                Case "init"
                    If Not _loadSent Then
                        _loadSent = True
                        Debug.WriteLine("[DrawioEditorForm] draw.io init received -> sending load")
                        SendLoadToDrawio()
                    End If

                Case "save"
                    If message.ContainsKey("xml") Then
                        Dim savedXml As String = TryCast(message("xml"), String)
                        If Not String.IsNullOrWhiteSpace(savedXml) Then
                            SaveDiagram(savedXml)
                        End If
                    End If

                Case "exit"
                    Me.Close()

                Case Else
                    Debug.WriteLine($"[DrawioEditorForm] draw.io event: {evtName}")
            End Select

        Catch ex As Exception
            Debug.WriteLine($"[DrawioEditorForm] OnWebMessageReceived error: {ex.Message}")
        End Try
    End Sub

    ''' <summary>
    ''' Sends the initial <c>load</c> payload to draw.io after the editor signals it is ready (<c>init</c>).
    ''' </summary>
    ''' <remarks>
    ''' This uses <see cref="CoreWebView2.ExecuteScriptAsync"/> to call a JavaScript function that posts the JSON payload
    ''' back to the window that emitted the <c>init</c> event (when using the bridge-script approach).
    ''' </remarks>
    Private Sub SendLoadToDrawio()
        Try
            If webView.CoreWebView2 Is Nothing Then Return

            Dim payload As New Dictionary(Of String, Object) From {
                {"action", "load"},
                {"xml", _xmlContent},
                {"title", _fileName}
            }

            Dim jsonText As String = Newtonsoft.Json.JsonConvert.SerializeObject(payload)

            ' Call the JS function that posts back to the captured init sender
            Dim script As String =
$"
(function() {{
  var ok = window.__riDrawioSendToDrawio({Newtonsoft.Json.JsonConvert.SerializeObject(jsonText)});
  console.log('[RI Drawio] __riDrawioSendToDrawio returned', ok);
}})();"

            webView.CoreWebView2.ExecuteScriptAsync(script)

        Catch ex As Exception
            Debug.WriteLine($"[DrawioEditorForm] SendLoadToDrawio error: {ex.Message}")
        End Try
    End Sub

    ''' <summary>
    ''' Writes the updated draw.io diagram XML to the target <c>.drawio</c> file.
    ''' </summary>
    ''' <param name="xmlContent">The diagram XML to persist.</param>
    ''' <remarks>
    ''' On success, the form title is temporarily updated to indicate that the file was saved.
    ''' </remarks>
    Private Sub SaveDiagram(xmlContent As String)
        Try
            IO.File.WriteAllText(_saveFilePath, xmlContent, System.Text.Encoding.UTF8)
            Debug.WriteLine($"[DrawioEditorForm] Saved: {_saveFilePath}")

            Me.Text = $"{AN} - Draw.io Diagram Editor (Saved)"
            System.Threading.Tasks.Task.Delay(2000).ContinueWith(
                Sub()
                    If Not Me.IsDisposed Then
                        Try
                            Me.Invoke(Sub() Me.Text = $"{AN} - Draw.io Diagram Editor")
                        Catch
                        End Try
                    End If
                End Sub)

        Catch ex As Exception
            Debug.WriteLine($"[DrawioEditorForm] SaveDiagram error: {ex.Message}")
            MessageBox.Show(
                $"Could not save the diagram: {ex.Message}",
                $"{AN} - Save Error",
                MessageBoxButtons.OK,
                MessageBoxIcon.Warning)
        End Try
    End Sub

    ''' <summary>
    ''' Releases WebView resources when the editor window is closing.
    ''' </summary>
    ''' <param name="e">Event arguments describing the close reason and allowing cancellation.</param>
    Protected Overrides Sub OnFormClosing(e As FormClosingEventArgs)
        Try
            webView?.Dispose()
        Catch
        End Try
        MyBase.OnFormClosing(e)
    End Sub


    ''' <summary>
    ''' Encodes bytes using base64url (RFC 4648 "URL and Filename Safe Alphabet") without padding.
    ''' </summary>
    ''' <param name="bytes">The bytes to encode.</param>
    ''' <returns>A base64url string with <c>=</c> padding removed and URL-safe characters substituted.</returns>
    Private Function ToBase64Url(bytes As Byte()) As String
        Dim s As String = Convert.ToBase64String(bytes)
        s = s.TrimEnd("="c).Replace("+"c, "-"c).Replace("/"c, "_"c)
        Return s
    End Function

End Class