' Part of "Red Ink for Word"
' Copyright (c) LawDigital Ltd., Switzerland. All rights reserved. For license to use see https://redink.ai.

' =============================================================================
' File: DrawioEditorForm.vb
' Purpose: Hosts the diagrams.net / draw.io editor inside a WinForms window using
'          WebView2. Loads a diagram from an XML string (mxfile) generated by the
'          application and allows the user to edit it. On save, the updated XML
'          can be persisted back to a local .drawio file.
' =============================================================================

Option Strict On
Option Explicit On

Imports System.Diagnostics
Imports System.Drawing
Imports System.IO
Imports System.IO.Compression
Imports System.Windows.Forms
Imports Microsoft.Web.WebView2.Core
Imports Microsoft.Web.WebView2.WinForms
Imports SharedLibrary.SharedLibrary.SharedMethods

Public Class DrawioEditorForm
    Inherits Form

    Private WithEvents webView As WebView2
    Private ReadOnly _xmlContent As String
    Private ReadOnly _saveFilePath As String
    Private ReadOnly _fileName As String

    Private _loadSent As Boolean = False

    Private Const DRAWIO_EMBED_URL As String =
        "https://embed.diagrams.net/?embed=1&proto=json&spin=1&saveAndExit=1&noSaveBtn=0"

    ' NEW: offline gating
    Private ReadOnly _disableInternetAfterLoad As Boolean
    Private _offlineModeEnabled As Boolean = False
    Private _networkFilterInstalled As Boolean = False
    Private _navigationCompletedOnce As Boolean = False

    ''' <summary>
    ''' Creates a new draw.io editor window that loads an existing diagram from XML and can save it back to disk.
    ''' </summary>
    Public Sub New(xmlContent As String, saveFilePath As String, Optional disableInternetAfterLoad As Boolean = False)
        _xmlContent = If(xmlContent, "")
        _saveFilePath = saveFilePath
        _fileName = IO.Path.GetFileNameWithoutExtension(saveFilePath)
        _disableInternetAfterLoad = disableInternetAfterLoad

        InitializeComponent()
        InitializeWebViewAsync()
    End Sub

    Private Sub InitializeComponent()
        Me.Text = $"{AN} - Draw.io Diagram Editor"
        Me.Width = 1400
        Me.Height = 900
        Me.StartPosition = FormStartPosition.CenterScreen
        Me.FormBorderStyle = FormBorderStyle.Sizable

        Try
            Dim bmp As New Bitmap(GetLogoBitmap(LogoType.Standard))
            Me.Icon = Icon.FromHandle(bmp.GetHicon())
        Catch
        End Try

        webView = New WebView2() With {.Dock = DockStyle.Fill}
        Me.Controls.Add(webView)
    End Sub

    Private Async Sub InitializeWebViewAsync()
        Try
            Dim userDataFolder As String = IO.Path.Combine(IO.Path.GetTempPath(), "RedInk_WebView2_Drawio")
            IO.Directory.CreateDirectory(userDataFolder)

            Dim env As CoreWebView2Environment = Await CoreWebView2Environment.CreateAsync(Nothing, userDataFolder)
            Await webView.EnsureCoreWebView2Async(env)

            webView.CoreWebView2.Settings.AreDevToolsEnabled = True
            webView.CoreWebView2.Settings.AreDefaultContextMenusEnabled = True

            AddHandler webView.CoreWebView2.WebMessageReceived, AddressOf OnWebMessageReceived
            AddHandler webView.CoreWebView2.NavigationCompleted, AddressOf OnNavigationCompleted

            ' NEW: install request filter/handler once (does nothing until _offlineModeEnabled = True)
            InstallOfflineNetworkFilter()

            Debug.WriteLine("[DrawioEditorForm] Loading local host HTML...")
            Dim html As String = BuildHostHtml(_xmlContent, _fileName)
            webView.CoreWebView2.NavigateToString(html)

        Catch ex As Exception
            Debug.WriteLine($"[DrawioEditorForm] WebView2 init error: {ex.Message}")
            MessageBox.Show(
                $"Could not initialize the diagram editor: {ex.Message}{vbCrLf}{vbCrLf}" &
                $"Your diagram has been saved to:{vbCrLf}{_saveFilePath}",
                $"{AN} - Error",
                MessageBoxButtons.OK,
                MessageBoxIcon.Error)
            Me.Close()
        End Try
    End Sub

    ' NEW: central place to install the handler
    Private Sub InstallOfflineNetworkFilter()
        If webView.CoreWebView2 Is Nothing Then Return
        If _networkFilterInstalled Then Return
        _networkFilterInstalled = True

        ' Intercept all requests; we will selectively deny once offline mode is enabled.
        webView.CoreWebView2.AddWebResourceRequestedFilter("*", CoreWebView2WebResourceContext.All)
        AddHandler webView.CoreWebView2.WebResourceRequested, AddressOf OnWebResourceRequested
    End Sub

    ' NEW: switch to offline mode
    Private Sub EnableOfflineMode()
        If Not _disableInternetAfterLoad Then Return
        If _offlineModeEnabled Then Return

        _offlineModeEnabled = True
        Debug.WriteLine("[DrawioEditorForm] Offline mode ENABLED (blocking http/https requests).")
    End Sub

    ' NEW: actually block
    Private Sub OnWebResourceRequested(sender As Object, e As CoreWebView2WebResourceRequestedEventArgs)
        Try
            If Not _offlineModeEnabled Then Return

            Dim uri As Uri = Nothing
            If Not Uri.TryCreate(e.Request.Uri, UriKind.Absolute, uri) Then Return

            ' Block internet requests. (data:, about:, chrome-webview:, etc. are not blocked.)
            If uri.Scheme.Equals("http", StringComparison.OrdinalIgnoreCase) OrElse
               uri.Scheme.Equals("https", StringComparison.OrdinalIgnoreCase) Then

                ' If you want to allow embed.diagrams.net even after offline, comment this out.
                ' Right now we block EVERYTHING over http/https once offline mode is enabled.

                Dim headers As String = "Content-Type: text/plain" & vbCrLf
                Dim stream As New MemoryStream(System.Text.Encoding.UTF8.GetBytes("Blocked by host (offline mode)."))

                e.Response = webView.CoreWebView2.Environment.CreateWebResourceResponse(
                    stream,
                    403,
                    "Forbidden",
                    headers)

                Debug.WriteLine($"[DrawioEditorForm] BLOCKED: {e.Request.Uri}")
            End If

        Catch ex As Exception
            Debug.WriteLine($"[DrawioEditorForm] OnWebResourceRequested error: {ex.Message}")
        End Try
    End Sub

    Private Function BuildHostHtml(xml As String, title As String) As String
        Dim xmlJs As String = Newtonsoft.Json.JsonConvert.SerializeObject(xml)
        Dim titleJs As String = Newtonsoft.Json.JsonConvert.SerializeObject(title)

        Return $"<!doctype html>
<html>
<head>
  <meta charset=""utf-8"">
  <title>{AN} - draw.io</title>
  <style>
    html, body {{ margin:0; padding:0; height:100%; overflow:hidden; }}
    #frame {{ width:100%; height:100%; border:0; }}
  </style>
</head>
<body>
  <iframe id=""frame"" src=""{DRAWIO_EMBED_URL}"" allow=""clipboard-read; clipboard-write""></iframe>

  <script>
    (function() {{
      const frame = document.getElementById('frame');
      const xml = {xmlJs};
      const title = {titleJs};

      function logToHost(obj) {{
        try {{
          if (window.chrome && window.chrome.webview) {{
            window.chrome.webview.postMessage(JSON.stringify(obj));
          }}
        }} catch (e) {{}}
      }}

      window.addEventListener('message', function(evt) {{
        if (!evt || !evt.data) return;
        if (typeof evt.data !== 'string') return;

        logToHost({{ event: 'drawio_msg', data: evt.data.substring(0, 400) }});

        let msg = null;
        try {{ msg = JSON.parse(evt.data); }} catch (e) {{ return; }}

        if (msg.event === 'init') {{
          const loadMsg = {{
            action: 'load',
            xml: xml,
            title: title
          }};
          frame.contentWindow.postMessage(JSON.stringify(loadMsg), '*');
          logToHost({{ event: 'ri_loaded_sent' }});
        }}

        if (msg.event === 'save') {{
          logToHost(msg);
        }}

        if (msg.event === 'exit') {{
          logToHost(msg);
        }}
      }}, false);

      logToHost({{ event: 'ri_host_ready' }});
    }})();
  </script>
</body>
</html>"
    End Function

    Private Sub OnNavigationCompleted(sender As Object, e As CoreWebView2NavigationCompletedEventArgs)
        If Not e.IsSuccess Then
            Debug.WriteLine($"[DrawioEditorForm] Navigation failed: {e.WebErrorStatus}")
            Return
        End If

        Debug.WriteLine("[DrawioEditorForm] Navigation completed.")

        ' NEW: after the host page has loaded once, enable offline mode if requested.
        If Not _navigationCompletedOnce Then
            _navigationCompletedOnce = True
            EnableOfflineMode()
        End If
    End Sub

    Private Sub OnWebMessageReceived(sender As Object, e As CoreWebView2WebMessageReceivedEventArgs)
        Try
            Dim messageString As String = e.TryGetWebMessageAsString()
            If String.IsNullOrEmpty(messageString) Then Return

            Debug.WriteLine($"[DrawioEditorForm] <- {If(messageString.Length > 200, messageString.Substring(0, 200), messageString)}")

            Dim message As Dictionary(Of String, Object) = Nothing
            Try
                message = Newtonsoft.Json.JsonConvert.DeserializeObject(Of Dictionary(Of String, Object))(messageString)
            Catch
                message = Nothing
            End Try
            If message Is Nothing Then Return

            Dim evtName As String = Nothing
            If message.ContainsKey("event") Then evtName = TryCast(message("event"), String)
            If String.IsNullOrEmpty(evtName) Then Return

            Select Case evtName
                Case "ri_bridge_ready"
                    Debug.WriteLine("[DrawioEditorForm] Bridge ready (JS -> .NET works). Waiting for draw.io init...")

                Case "init"
                    If Not _loadSent Then
                        _loadSent = True
                        Debug.WriteLine("[DrawioEditorForm] draw.io init received -> sending load")
                        SendLoadToDrawio()
                        EnableOfflineMode()
                    End If

                Case "save"
                    If message.ContainsKey("xml") Then
                        Dim savedXml As String = TryCast(message("xml"), String)
                        If Not String.IsNullOrWhiteSpace(savedXml) Then
                            SaveDiagram(savedXml)
                        End If
                    End If

                Case "exit"
                    Me.Close()

                Case Else
                    Debug.WriteLine($"[DrawioEditorForm] draw.io event: {evtName}")
            End Select

        Catch ex As Exception
            Debug.WriteLine($"[DrawioEditorForm] OnWebMessageReceived error: {ex.Message}")
        End Try
    End Sub

    Private Sub SendLoadToDrawio()
        Try
            If webView.CoreWebView2 Is Nothing Then Return

            Dim payload As New Dictionary(Of String, Object) From {
                {"action", "load"},
                {"xml", _xmlContent},
                {"title", _fileName}
            }

            Dim jsonText As String = Newtonsoft.Json.JsonConvert.SerializeObject(payload)

            Dim script As String =
$"
(function() {{
  var ok = window.__riDrawioSendToDrawio({Newtonsoft.Json.JsonConvert.SerializeObject(jsonText)});
  console.log('[RI Drawio] __riDrawioSendToDrawio returned', ok);
}})();"

            webView.CoreWebView2.ExecuteScriptAsync(script)

        Catch ex As Exception
            Debug.WriteLine($"[DrawioEditorForm] SendLoadToDrawio error: {ex.Message}")
        End Try
    End Sub

    Private Sub SaveDiagram(xmlContent As String)
        Try
            IO.File.WriteAllText(_saveFilePath, xmlContent, System.Text.Encoding.UTF8)
            Debug.WriteLine($"[DrawioEditorForm] Saved: {_saveFilePath}")

            Me.Text = $"{AN} - Draw.io Diagram Editor (Saved)"
            System.Threading.Tasks.Task.Delay(2000).ContinueWith(
                Sub()
                    If Not Me.IsDisposed Then
                        Try
                            Me.Invoke(Sub() Me.Text = $"{AN} - Draw.io Diagram Editor")
                        Catch
                        End Try
                    End If
                End Sub)

        Catch ex As Exception
            Debug.WriteLine($"[DrawioEditorForm] SaveDiagram error: {ex.Message}")
            MessageBox.Show(
                $"Could not save the diagram: {ex.Message}",
                $"{AN} - Save Error",
                MessageBoxButtons.OK,
                MessageBoxIcon.Warning)
        End Try
    End Sub

    Protected Overrides Sub OnFormClosing(e As FormClosingEventArgs)
        Try
            webView?.Dispose()
        Catch
        End Try
        MyBase.OnFormClosing(e)
    End Sub

    Private Function ToBase64Url(bytes As Byte()) As String
        Dim s As String = Convert.ToBase64String(bytes)
        s = s.TrimEnd("="c).Replace("+"c, "-"c).Replace("/"c, "_"c)
        Return s
    End Function

End Class